### ISSUE TITLE
 mailnag-config error on antergos/Arch + Gnome 3.22.2

### ISSUE THREAD

**Issue by shuvo-paul** [pulb/mailnag#149]
Getting following errors when trying to run mailnag-config on antergos/Arch with Gnome 3.22.2.

`Traceback (most recent call last):
  File "/usr/bin/mailnag-config", line 61, in <module>
    if __name__ == "__main__":  main()
  File "/usr/bin/mailnag-config", line 44, in main
    confwin = ConfigWindow()
  File "/usr/lib/python2.7/site-packages/Mailnag/configuration/configwindow.py", line 100, in __init__
    self._accountman = AccountManager(CredentialStore.from_string(self._cfg.get('core', 'credentialstore')))
  File "/usr/lib/python2.7/site-packages/Mailnag/common/credentialstore.py", line 75, in from_string
    cs = CredentialStore.get_default()
  File "/usr/lib/python2.7/site-packages/Mailnag/common/credentialstore.py", line 66, in get_default
    CredentialStore._instance = SupportedCredentialStores[_credentialstoretype]()
  File "/usr/lib/python2.7/site-packages/Mailnag/common/credentialstore.py", line 96, in __init__
    raise KeyringUnlockException('Failed to unlock default keyring')
Mailnag.common.credentialstore.KeyringUnlockException: Failed to unlock default keyring
`

**Comment by shuvo-paul** [comment]
I just tried again and it is now working fine.
Thanks to developers.
