### ISSUE TITLE
can_reach exception not handled

### ISSUE THREAD

**Issue by c4pp4** [pulb/mailnag#220]
v2.2.0
```
ERROR (2021-03-30 23:23:14): Caught an exception.
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/Mailnag/daemon/mailnagdaemon.py", line 165, in _start
    if not self._wait_for_inet_connection():
  File "/usr/lib/python3.8/site-packages/Mailnag/daemon/mailnagdaemon.py", line 212, in _wait_for_inet_connection
    if self._conntest.is_offline():
  File "/usr/lib/python3.8/site-packages/Mailnag/daemon/conntest.py", line 47, in is_offline
    return (not self._monitor.can_reach(Gio.NetworkAddress.new(TEST_HOST, 8080)))
gi.repository.GLib.GError: g-resolver-error-quark: Error resolving “www.google.com”: Temporary failure in name resolution (1)
INFO (2021-03-30 23:23:14): Shutting down...
```

**Comment by pulb** [comment]
Wow. Thank you very much for that exception, glib.

Thanks for reporting, very appreciated! Will be fixed in the next release.

BR
Patrick

Am 31. März 2021 00:10:14 MESZ schrieb c4pp4 ***@***.***>:
