### ISSUE TITLE
Configuration fails

### ISSUE THREAD

**Issue by zoidby** [pulb/mailnag#234]
Hi,

after adding an account in mailnag-config, closing it doesn’t write the config and produces this output instead:

```
> mailnag-config 
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/Mailnag/configuration/configwindow.py", line 392, in _on_config_window_deleted
    self._save_config()	
  File "/usr/lib/python3.10/site-packages/Mailnag/configuration/configwindow.py", line 155, in _save_config
    self._accountman.save_to_cfg(self._cfg)
  File "/usr/lib/python3.10/site-packages/Mailnag/common/accounts.py", line 312, in save_to_cfg
    self._secretstore.set(self._get_account_id(acc.user, acc.server, acc.imap), acc.password,
  File "/usr/lib/python3.10/site-packages/Mailnag/common/secretstore.py", line 49, in set
    Secret.password_store_sync(
gi.repository.GLib.GError: g-dbus-error-quark: Object does not exist at path “/org/freedesktop/secrets/collection/login” (19)


```

**Comment by akwala** [comment]
Same issue but a different `gi.repository.GLib.GError`:
```
$ mailnag-config
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/Mailnag/configuration/configwindow.py", line 392, in _on_config_window_deleted
    self._save_config()
  File "/usr/lib/python3/dist-packages/Mailnag/configuration/configwindow.py", line 155, in _save_config
    self._accountman.save_to_cfg(self._cfg)
  File "/usr/lib/python3/dist-packages/Mailnag/common/accounts.py", line 312, in save_to_cfg
    self._secretstore.set(self._get_account_id(acc.user, acc.server, acc.imap), acc.password,
  File "/usr/lib/python3/dist-packages/Mailnag/common/secretstore.py", line 49, in set
    Secret.password_store_sync(
gi.repository.GLib.GError: g-dbus-error-quark: The name org.freedesktop.secrets was not provided by any .service files (2)
```
Mailnag 2.2.0
Python 3.10

Operating System: Kubuntu 22.04
KDE Plasma Version: 5.24.6
KDE Frameworks Version: 5.95.0
Qt Version: 5.15.3
Kernel Version: 5.15.0-47-generic (64-bit)

**Comment by ShiroiBara** [comment]
I have solved this by installing gnome-keyring package (Arch Linux).
