### ISSUE TITLE
ModuleNotFoundError: No module named 'imp'

### ISSUE THREAD

**Issue by kparal** [pulb/mailnag#244]
Python 3.12 no longer contains module [imp](https://docs.python.org/3/library/imp.html). Mailnag crashes immediately on start:

```
$ mailnag
Traceback (most recent call last):
  File "/usr/bin/mailnag", line 43, in <module>
    from Mailnag.daemon.mailnagdaemon import MailnagDaemon
  File "/usr/lib/python3.12/site-packages/Mailnag/daemon/mailnagdaemon.py", line 26, in <module>
    from Mailnag.daemon.mailchecker import MailChecker
  File "/usr/lib/python3.12/site-packages/Mailnag/daemon/mailchecker.py", line 26, in <module>
    from Mailnag.common.plugins import HookTypes
  File "/usr/lib/python3.12/site-packages/Mailnag/common/plugins.py", line 20, in <module>
    import imp
ModuleNotFoundError: No module named 'imp'
```

**Comment by knurd** [comment]
FWIW, this is caused my the removal of imp in in Python 3.12, which is the default by Fedora 39+ (which is likely what @kparal uses). This for now will soon be worked-around in Fedora by requiring python3-zombie-imp. But for the record: that only got me one step further, as I a ssl function used by mailnag was also removed. See https://github.com/pulb/mailnag/issues/245 for details.

**Comment by jezek** [comment]
Pardon my intrusion. On manjaro linux I get this error too.

**Comment by JanBluePix** [comment]
after update on Manjaro Linux I get the same error with Python 3.12.3

**Comment by fijarom** [comment]
This issue still persists in November 2025. I'm on Arch Linux and using Python 3.13.7
