### ISSUE TITLE
KDE keyring...

### ISSUE THREAD

**Issue by timgooders** [pulb/mailnag#79]
Trying this is Kubuntu 14.04 this is what I get:

/usr/bin/mailnag-config
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/Mailnag/config.py", line 54, in <module>
    if __name__ == "__main__":  main()
  File "/usr/lib/python2.7/dist-packages/Mailnag/config.py", line 37, in main
    confwin = ConfigWindow()
  File "/usr/lib/python2.7/dist-packages/Mailnag/configuration/configwindow.py", line 94, in __init__
    self._accounts = AccountList()
  File "/usr/lib/python2.7/dist-packages/Mailnag/common/accounts.py", line 175, in __init__
    self._keyring = Keyring()
  File "/usr/lib/python2.7/dist-packages/Mailnag/common/keyring.py", line 47, in __init__
    raise KeyringUnlockException('Failed to unlock default keyring')
common.keyring.KeyringUnlockException: Failed to unlock default keyring

**Comment by pulb** [comment]
Fixed in Mailnag 1.1.
